# Generated by Django 3.2.3 on 2021-05-31 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urlshortener', '0005_alter_ommnurl_shortcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ommn_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='urlshortener.ommnurl')),
            ],
        ),
    ]
