# Generated by Django 3.2.3 on 2021-05-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ommnurl',
            name='shortcode',
            field=models.CharField(default='defcode', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
