# Generated by Django 3.2.3 on 2021-05-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ommnurl',
            name='shortcode',
            field=models.CharField(default='defcode', max_length=15, unique=True),
        ),
    ]
