# Generated by Django 3.2.3 on 2021-05-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_alter_ommnurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ommnurl',
            name='shortcode',
            field=models.CharField(blank=True, default='defcode', max_length=15, unique=True),
        ),
    ]
