# Generated by Django 3.2.3 on 2021-05-26 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_ommnurl_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ommnurl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ommnurl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
